// Generated by CoffeeScript 1.3.3
(function() {
  var Article, P, bd, fs, next, path;

  P = require('autoresolve');

  path = require('path');

  fs = require('fs-extra');

  next = require('nextflow');

  bd = require('batchdir');

  Article = (function() {

    function Article(site) {
      this.site = site;
    }

    Article.prototype.createNew = function(title, tags, callback) {
      var articlePath, dir, flow, sp;
      if (typeof tags === 'string') {
        tags = tags.split(',').map(function(e) {
          return e.trim();
        });
      }
      articlePath = this.site.addArticleEntry(title, tags);
      dir = path.dirname(path.join(this.site.sitePath, articlePath));
      sp = this.site.sitePath;
      return next(flow = {
        ERROR: function(err) {
          return callback(err);
        },
        makeIt: function() {
          return bd(dir).mkdir(this.next);
        },
        done: function() {
          var file;
          file = path.join(sp, articlePath);
          return fs.writeFile(file, '', function(err) {
            return callback(err, file);
          });
        }
      });
    };

    Article.create = function(site) {
      return new Article(site);
    };

    return Article;

  })();

  module.exports.Article = Article;

}).call(this);
