// Generated by CoffeeScript 1.3.3
(function() {
  var ContentWalker, EventEmitter, fs, mde, path, walker,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  walker = require('walker');

  path = require('path');

  fs = require('fs-extra');

  EventEmitter = require('events').EventEmitter;

  mde = require('markdown-extra');

  ContentWalker = (function(_super) {

    __extends(ContentWalker, _super);

    function ContentWalker(site, dir) {
      this.site = site;
      this.dir = path.join(this.site.path, dir);
    }

    ContentWalker.prototype.walk = function(lastPublished) {
      lastPublished = lastPublished || new Date(0);
      walker = walker(this.articleDir);
      walker.on('file', function(file, stat) {
        if (stat.mtime > lastPublished) {
          return fs.readFile(file, 'utf8', function(err, text) {
            return this.emit('content', file);
          });
        }
      });
      walker.on('error', function(err) {
        return this.emit('error', err);
      });
      return walker.on('end', function() {
        return this.emit('end');
      });
    };

    ContentWalker.create = function(site) {
      return new ArticleWalker(site);
    };

    return ContentWalker;

  })(EventEmitter);

  /*
  PRIVATE FUNCTIONS
  */


}).call(this);
