// Generated by CoffeeScript 1.3.3
(function() {
  var Content, S, mde;

  S = require('string');

  mde = require('markdown-extra');

  Content = (function() {

    function Content(text) {
      var _getContent, _getMetaData, _getTitle;
      this.text = text;
      this._metadata = null;
      _getMetaData = function() {
        var yml,
          _this = this;
        if (!this._metadata) {
          this._metadata = {};
          yml = mde.metadata(this.text);
          S(yml).lines().forEach(function(line) {
            var data;
            if (S(line).contains(':')) {
              data = line.split(':');
              return _this._metadata[data[0].trim()] = data[1].trim();
            }
          });
          if (this._metadata['tags']) {
            if (S(this._metadata['tags']).contains(',')) {
              this._metadata['tags'] = this._metadata['tags'].split(',').map(function(tag) {
                return tag.trim();
              });
            } else {
              this._metadata['tags'] = [this._metadata['tags']];
            }
          }
          if (this._metadata['publish']) {
            try {
              this._metadata['publish'] = Date.parse(this._metadata.publish);
            } catch (e) {

            }
          }
        }
        return this._metadata;
      };
      Object.defineProperty(this, 'metadata', {
        enumerable: true,
        get: _getMetaData
      });
      this._title = null;
      _getTitle = function() {
        if (!this._title) {
          this._title = mde.heading(this.text);
        }
        return this._title;
      };
      Object.defineProperty(this, 'title', {
        enumerable: true,
        get: _getTitle
      });
      this._content = null;
      _getContent = function() {
        if (!this._content) {
          this._content = mde.content(this.text);
        }
        return this._content;
      };
      Object.defineProperty(this, 'content', {
        enumerable: true,
        get: _getContent
      });
    }

    Content.create = function(content) {
      return new Content(content || '');
    };

    return Content;

  })();

  module.exports.Content = Content;

}).call(this);
